# Generated by Django 4.1.3 on 2023-05-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_student_10_student_11_student_9_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_11',
            name='gender',
            field=models.CharField(choices=[('эркек', 'Эркек'), ('кыз', 'Кыз')], max_length=120, verbose_name='Жынысы'),
        ),
    ]
