# Generated by Django 4.1.3 on 2023-05-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_student_11_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_11',
            name='gender',
            field=models.CharField(choices=[('эркек', 'Эркек'), ('кыз', 'Кыз')], default='эркек', max_length=120, verbose_name='Жынысы'),
        ),
    ]
