# Generated by Django 4.1.3 on 2023-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.CharField(max_length=120, verbose_name='Өнөрлөрү(Жөндөмдүүлүктөрү)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_of_dud_mum',
            field=models.CharField(max_length=120, verbose_name='Ата-энесини аты-жөнү'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(max_length=120, verbose_name='Жашаган жери'),
        ),
        migrations.AlterField(
            model_name='student',
            name='success',
            field=models.CharField(max_length=120, verbose_name='Ийгиликтери'),
        ),
    ]
