# Generated by Django 4.1.3 on 2023-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_alter_student_interesting_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_of_year',
            field=models.CharField(choices=[('7-класс', '7-класс'), ('8-класс', '8-класс'), ('9-класс', '9-класс'), ('10-класс', '10-класс')], default='7-класс', max_length=120, null=True, verbose_name='Бүтүргөн классы'),
        ),
    ]
