# Generated by Django 4.1.3 on 2023-05-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_alter_student_class_of_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_11',
            options={'verbose_name': '7-Класс', 'verbose_name_plural': '7-Классс'},
        ),
        migrations.AlterField(
            model_name='student_11',
            name='gender',
            field=models.CharField(max_length=120, null=True, verbose_name='Жынысы'),
        ),
    ]
